simulation:
 # number or repetitions
 repetitions: 3
 # simulation output folder
 output_folder: "output"
 # simulation output file
 output_file: "scenario1_scaffold_exp2.json"
 # model
 model_name: "mnist"
 # metric
 metric: "accuracy"
 # maximum number of rounds
 num_rounds: 50
 # list of stopping conditions (OR) for ending the simulation
 stop_conds:
   # global model accuracy (during evaluation)
   metric: 1
   # global model loss (during evaluation)
   loss: 0
 # initialization policy
 initializer: "default"
 # fixing random state for reproducibility
 seed: none
 # set the TensorFlow verbosity, 0 = silent, 1 = progress bar, 2 = one line per epoch
 tf_verbosity: 1
 # number of concurrent processes
 num_processes: 1

algorithms:
 federated_algorithm: "scaffold"
 fit:
   # algorithm used for the FL aggregation
   aggregation: "fedavg"
   # algorithm used for the clients selection
   selection: "random"
   # algorithm used for the update optimizer
   update: "static"
   # algorithm used for the local data optimizer
   data: "random"
   # parameters used by the algorithm
   params:
     # fraction of devices used for the computation
     k: 0.5
     # number of epochs executed for fit for each round
     epochs: 20
     # batch size used for fit for each round
     batch_size: 10
     # number of examples used for fit for each round
     num_examples: 30
 eval:
   selection: "random"
   update: "static"
   data: "random"
   params:
     k: 0.5
     epochs: 20
     batch_size: 10
     num_examples: 20
 # optimizer used (local iteration) string or optimizer instance
 optimizer: "sgd"

devices:
 # total number of devices (D)
 num: 60
 # probability a device is available for a round
 p_available: 0.7
 # probability a device fails during a round
 p_fail: 0.1
 # number of malicious devices
 adversary_num: 0

computation:
 # mean and variance of number of computed iterations/second per device (among devices) [iter/s]
 ips_mean: 100
 ips_var: 50

energy:
 # mean and variance of energy available at each device [mWh]
 avail_mean: 3000
 avail_var: 100
 # power consumption for 1 second of computation [mW/s]
 pow_comp_s: 100
 # power consumption for 1 second of network used [mW/s]
 pow_net_s: 200

network:
 # mean and variance of network speed available at each device [params/s]
 speed_mean: 100000
 speed_var: 1000

data:
 # mean and variance of number of examples available at each device
 num_examples_mean: 100
 num_examples_var: 20
 # use non-i.d.d data
 non_iid_partitions: 0.1
 # percentage of mislabelled data
 mislabelling_percentage: 0
